import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';

import {
  IgxGridModule,
  IgxTreeGridModule,
  IgxHierarchicalGridModule,
  IgxPivotGridModule,
  IgxComboModule,
  IgxSimpleComboModule,
  IgxSelectModule,
  IgxInputGroupModule,
  IgxDatePickerModule,
  IgxTimePickerModule,
  IgxDateRangePickerModule,
  IgxCalendarModule,
  IgxTabsModule,
  IgxStepperModule,
  IgxAccordionModule,
  IgxListModule,
  IgxCardModule,
  IgxDialogModule,
  IgxSnackbarModule,
  IgxButtonModule,
  IgxRippleModule,
  IgxTooltipModule,
  IgxDragDropModule,
  IgxChipsModule,
  IgxBadgeModule,
  IgxAvatarModule,
  IgxIconModule,
  IgxProgressBarModule,
  IgxSliderModule,
  IgxSwitchModule,
  IgxCheckboxModule,
  IgxRadioModule,
  IgxExpansionPanelModule,
  IgxBannerModule,
  IgxNavbarModule,
  IgxNavigationDrawerModule,
  IgxBottomNavModule,
  IgxDividerModule,
  IgxOverlayService,
} from 'igniteui-angular';

import { VerifyComponent } from './verify/verify.component';

@NgModule({
  declarations: [VerifyComponent],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    FormsModule,
    ReactiveFormsModule,
    IgxGridModule,
    IgxTreeGridModule,
    IgxHierarchicalGridModule,
    IgxPivotGridModule,
    IgxComboModule,
    IgxSimpleComboModule,
    IgxSelectModule,
    IgxInputGroupModule,
    IgxDatePickerModule,
    IgxTimePickerModule,
    IgxDateRangePickerModule,
    IgxCalendarModule,
    IgxTabsModule,
    IgxStepperModule,
    IgxAccordionModule,
    IgxListModule,
    IgxCardModule,
    IgxDialogModule,
    IgxSnackbarModule,
    IgxButtonModule,
    IgxRippleModule,
    IgxTooltipModule,
    IgxDragDropModule,
    IgxChipsModule,
    IgxBadgeModule,
    IgxAvatarModule,
    IgxIconModule,
    IgxProgressBarModule,
    IgxSliderModule,
    IgxSwitchModule,
    IgxCheckboxModule,
    IgxRadioModule,
    IgxExpansionPanelModule,
    IgxBannerModule,
    IgxNavbarModule,
    IgxNavigationDrawerModule,
    IgxBottomNavModule,
    IgxDividerModule,
  ],
  providers: [IgxOverlayService],
  bootstrap: [VerifyComponent],
})
export class AppModule {}
