// VERIFY_INJECT_POINT
// This file is overwritten by .claude/skills/scaffold-and-verify/scripts/verify-snippet.sh
// and reset to this template after each verification run.
// DO NOT edit this file manually.

import { Component } from '@angular/core';

@Component({
  selector: 'igx-verify',
  template: `<p>verify placeholder</p>`,
})
export class VerifyComponent {}
